### ISSUE TITLE
It bricked my device

### ISSUE THREAD

**Issue by harryparsons21** [stman/OpenWRT-19.07.2-factory-tar-file-for-Ubiquiti-EdgeRouter-x#1]
It no longer works

**Comment by user8446** [comment]
I just flashed an EdgeRouter X and it still works as expected. This was my first time doing that model and there are some particular steps after reading [here](https://openwrt.org/toh/ubiquiti/edgerouter_x_er-x_ka) and [here.](https://forum.openwrt.org/t/operational-openwrt-19-07-2-factory-tar-file-for-edgerouter-x/64153/31).

Factory defaulted with reset button
Connected eth0 to your existing router and access the stock GUI
Flashed this repo's factory image with the GUI
Connect to eth1 via static IP and SSH into OpenWrt
Put the OpenWrt sysupgrade bin file in `/tmp`
`sysupgrade -n -F /tmp/openwrt-21.02.3-ramips-mt7621-ubnt_edgerouter-x-squashfs-sysupgrade.bin`
(it won't work without the force switch... you'll get mismatch errors)
