### ISSUE TITLE
21.02 Does not build factory-tar-file

### ISSUE THREAD

**Issue by Jaska8** [stman/OpenWRT-19.07.2-factory-tar-file-for-Ubiquiti-EdgeRouter-x#3]
Hi.
I tried building valid factory.tar file for my edgerouter-x but it does not appear on build dir.
I've done everything what was instructed and tried your dot.conf but to no avail.
Trying your factory tar file will just soft brick my router.
SSH works but I can't log into it because I can't access webui and set the password.

**Comment by snoweer** [comment]
Hi，
I have the same problem as Jaska8.
21.02 does not build the factory tar file on ubuntu-20.04.2.0-desktop-amd64.
Please help us.

**Comment by JosiahMcGurty** [comment]
Same issue here. Cannot get the factory tar file with 19.07 or 21.02
Would you be willing to share the file you generated

**Comment by cyounkins** [comment]
I built 21.02 factory files here: https://github.com/cyounkins/edgerouter-factory

**Comment by stman** [comment]
Yep, sorry, it was not working for 21.02, but hopefully @cyounkins  found another way to build it. Just read above and have a look at his bighub repo to get his menuconfig.txt file to create the build. Thanks a lot again @cyounkins . Going to build it now again and see how it goes. Will post my results here, and update my page on github once I succeed.

Kind regards,

Fred.

**Comment by stman** [comment]
> Hi. I tried building valid factory.tar file for my edgerouter-x but it does not appear on build dir. I've done everything what was instructed and tried your dot.conf but to no avail. Trying your factory tar file will just soft brick my router. SSH works but I can't log into it because I can't access webui and set the password.

Hello.

I have updated my repository for the compilation of version 21.02.

I'm on my way to update for version 22.03 too.

Thanks again to @cyounkins for his help in improving my own work.
